JudoKit-iOS.xcodeproj/project.pbxproj
JudoKit-iOSTests/Modules/Sevices/TransactionService/JPTransactionServiceTest.swift
Source/Modules/Transaction/Interactor/JPTransactionInteractor.m
Source/Services/Transaction/JPTransactionService.m
Source/Services/iDEAL/JPIDEALService.m

Related to: https://thedojo.atlassian.net/browse/EP-1042

Added unique payment reference for each DEBUG transaction

---

Resources/de.lproj/Localizable.strings
Resources/en.lproj/Localizable.strings
Resources/fr.lproj/Localizable.strings
Resources/nl.lproj/Localizable.strings

update translation for secure_server_transmission key

EP-1056  iOS - Update Security Message from SSL to TLS

---

.sonarscan
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/project.pbxproj
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/AppDelegate.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Base.lproj/Main.storyboard
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/MainViewController.h
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/MainViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/Service/ExampleAppStorage.h
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/Service/ExampleAppStorage.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/Service/SampleAppStoreUserDefaults.h
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/Service/SampleAppStoreUserDefaults.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/PBBA/PBBAViewController.m
JudoKit-iOSTests/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractorTest.swift
JudoKit-iOSTests/Modules/PaymentMethods/Mocks/JPPaymentMethodsInteractorMock.swift
JudoKit-iOSTests/Sevices/PBBA/JPPBBAServiceTest.swift
Source/JudoKit.h
Source/JudoKit.m
Source/Models/PBBAConfiguration/JPPBBAConfiguration.h
Source/Models/PBBAConfiguration/JPPBBAConfiguration.m
Source/Modules/PaymentMethods/Builder/JPPaymentMethodsBuilder.m
Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.h
Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.h
Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
Source/Services/PBBA/JPPBBAService.h
Source/Services/PBBA/JPPBBAService.m

implement deeplink handle when app is not in memory

EP-1112 Improve PbBa Deeplinking

---

JudoKit-iOSTests/Sevices/ConfigurationValidator/JPConfigurationValidationServiceTest.swift
Source/Models/Constants/JPConstants.h
Source/Modules/Transaction/View/JPTransactionViewController.h
Source/Services/ConfigurationValidation/JPConfigurationValidationService.m

add regex for judokit validation
updated tests

EP-976  SDK - Add Judo ID Validation

---

Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
Source/View/JPCardInputView/JPCardInputView.m

check bottom constraint for nil, and do not recreate it

EP-1165  [iOS] BUGs with auto layout system and crashing when saving cards in payment methods widget

---

Source/JudoKit.h
Source/JudoKit.m
Source/Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.m
Source/Services/ApplePay/JPApplePayService.h
Source/Services/ApplePay/JPApplePayService.m
Source/Services/ConfigurationValidation/JPConfigurationValidationService.h
Source/Services/ConfigurationValidation/JPConfigurationValidationService.m

Not too happy about presenting the Apple Pay sheet in the Interactor, but the alternative is dragging the JPApplePayService and completion handler all over the place.

Added methods that return the Judo UIViewController instances

---

Source/Extensions/JPError/JPError+Additions.h
Source/Extensions/JPError/JPError+Additions.m
Source/Models/Session/JPSession.m

keep old implemetation for JPTransactionResultError type un result
add new static error for declined card

EP-1204 - card deeclined issue

---

JudoKit_iOS.xcodeproj/project.pbxproj
JudoKit_iOSTests/Extensions/NSNumberFormatter/NSNumberFormatterTests.swift
JudoKit_iOSTests/JudoKit_iOSTests-Bridging-Header.h
Source/Extensions/NSNumberFormatter/NSNumberFormatter+Additions.h
Source/Extensions/NSNumberFormatter/NSNumberFormatter+Additions.m
Source/Modules/PaymentMethods/View/Subviews/JPPaymentMethodsHeaderView.m
Source/Modules/Transaction/Interactor/JPTransactionInteractor.m

Added formatted currency to the SDK

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/MainViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/DemoFeature.h
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/DemoFeature.m
Source/JudoKit.h
Source/JudoKit.m
Source/Services/ApiService/JPApiService.h
Source/Services/ApiService/JPApiService.m

add new method to api service
update sample app

EP-1241-Get Transaction

---

JudoKit_iOS.xcodeproj/project.pbxproj

Seems to fix the test issue. What I did:

Attempted fix for failing test target build

---

JudoKit_iOS.xcodeproj/project.pbxproj

Removed `Embed Frameworks` section to solve the `ITMS-90685` errors

- Fixed embedded frameworks issue

---

JudoKit-iOS.podspec
JudoKit_iOS.xcodeproj/project.pbxproj
JudoKit_iOSTests/Extensions/JPError/JPErrorAdditionsTests.swift
Source/JudoKit.h

- Added fix for Apple Pay 'Cancel' event callbacks not triggering 
- Added UI Test setup
- Improved backend error parsing logic

Release 2.1.2

---

Examples/SwiftExampleApp/SwiftExampleApp.xcodeproj/project.pbxproj
Examples/SwiftExampleApp/SwiftExampleApp/AppCoordinator.swift
Examples/SwiftExampleApp/SwiftExampleApp/AppDelegate.swift
Examples/SwiftExampleApp/SwiftExampleApp/Info.plist
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/Components/FeatureCell.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/HomeInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/HomeViewController.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/Services/FeatureService.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAModule.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAViewController.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Results/Components/ResultsCell.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenModule.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenViewController.swift
Source/Services/PBBA/JPPBBAService.m

- Added PBBA functionality to the Swift sample app;
- Added deeplink support for both active and closed app scenarios;
- Moved Token transaction logic from TokenInteractor to the FeatureService;
- Added some UI improvements to look better in dark mode;

[EP-1788] Added PBBA and deeplink support

---

Examples/SwiftExampleApp/SwiftExampleApp.xcodeproj/project.pbxproj
Examples/SwiftExampleApp/SwiftExampleApp/AppCoordinator.swift
Examples/SwiftExampleApp/SwiftExampleApp/AppDelegate.swift
Examples/SwiftExampleApp/SwiftExampleApp/Info.plist
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/Components/FeatureCell.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/HomeInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/HomeViewController.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/Services/FeatureService.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAModule.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/PBBA/PBBAViewController.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Results/Components/ResultsCell.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenInteractor.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenModule.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/Token/TokenViewController.swift
Source/Services/PBBA/JPPBBAService.m

[EP-1789] Added token transactions with 3DS support

---

Source/Helpers/Functions.h
Source/Helpers/Functions.m
Source/Models/ApplePayConfiguration/JPApplePayConfiguration.h
Source/Models/ApplePayConfiguration/JPApplePayConfiguration.m
Source/Models/ApplePayWrappers/JPApplePayTypes.h
Source/Models/ApplePayWrappers/JPApplePayWrappers.m
Source/Models/CardDetails/JPCardDetails.m
Source/Models/Reachability/JPReachability.m
Source/Models/Response/JPResponse.h
Source/Models/Response/JPResponse.m
Source/Modules/PaymentMethods/View/Subviews/Cells/CardCell/JPPaymentMethodsCardCell.m
Source/Modules/PaymentMethods/View/Subviews/JPPaymentMethodsHeaderView.h
Source/Modules/PaymentMethods/View/Subviews/JPPaymentMethodsHeaderView.m
Source/Modules/Transaction/Interactor/JPTransactionInteractor.h
Source/Modules/Transaction/Presenter/JPTransactionPresenter.h
Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
Source/View/ApplePayButton/JPApplePayButton.h
Source/View/ApplePayButton/JPApplePayButton.m

- Fixed JPResponse amounts types mismatch
- Added judoId to string conversion
- clang-format

Fixed JPResponse amounts types mismatch

---

Cartfile.resolved
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/project.pbxproj
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/ApplePay/ApplePayViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/MainViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/PBBA/PBBAViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Result/Model/Result.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Result/ResultTableViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/TokenPay/PayWithCardTokenViewController.m
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Extensions/UIViewController+Additions.h
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Extensions/UIViewController+Additions.m
JudoKit_iOSTests/Modules/PaymentMethods/Mocks/JPPaymentMethodsRouterMock.swift
Source/Modules/3DSViewController/JP3DSViewController.m
Source/Modules/IDEALViewController/JPIDEALViewController.m
Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
Source/Modules/PaymentMethods/Router/JPPaymentMethodsRouter.h
Source/Modules/PaymentMethods/Router/JPPaymentMethodsRouter.m
Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
Source/Modules/Transaction/View/JPTransactionViewController.m
Source/Services/ApplePay/JPApplePayController.m

Fixes attempt to present a controller on a controller which is already presenting when SDK completion callback is invoked

Fixes attempt to present a controller on a controller which is already presenting

---

Examples/ObjectiveCExampleApp/ExportOptions.plist
Source/Models/3DSConfiguration/JP3DSConfiguration.m
Source/Services/CardTransactionService/JPCardTransactionService.m

also adding ExportOptions to the sample app in preparation to Firebase App Distribution

Fix sonar issues

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/project.pbxproj
Examples/ObjectiveCExampleApp/Podfile
Examples/ObjectiveCExampleApp/Podfile.lock
JudoKit-iOS.podspec
Source/JudoKit.h
Source/Modules/CardScanController/JPCardScanController.m

- Fixes `NSInvalidArgumentException - [__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]` in `JPCardScanController.m:224`

Crash fixes

---

Source/Models/Request/JPApplePayRequest.h
Source/Models/Request/JPApplePayRequest.m

Update Apple Pay paymentMethod payload

CT-2624 Update Apple Pay paymentMethod payload

---

Cartfile
Cartfile.resolved
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/project.pbxproj
Examples/ObjectiveCExampleApp/Podfile
JudoKit-iOS.podspec
Package.resolved
Package.swift
Source/JudoKit.h

- 3DS SDK version bump
- Package version bump

3DS SDK version bump

---

Source/Models/Request/JPApplePayRequest.h
Source/Models/Request/JPApplePayRequest.m

Changed from "ISOCountryCode" to "isoCountryCode" as ticket requests.
https://thedojo.atlassian.net/browse/CT-2806

CT-2806 isoCountryCode property adjusted

---

Source/Extensions/JPCardTransactionDetails/JPCardTransactionDetails+Additions.h
Source/Extensions/JPCardTransactionDetails/JPCardTransactionDetails+Additions.m
Source/Extensions/JPResponse/JPResponse+Additions.h
Source/Extensions/JPResponse/JPResponse+Additions.m
Source/Extensions/NSString/NSString+Additions.h
Source/Extensions/NSString/NSString+Additions.m
Source/Models/Response/JPResponse.m
Source/Models/ThreeDSecureTwo/JPThreeDSecureTwo.h
Source/Services/ApiService/Session/JPSession.m
Source/Services/CardTransactionService/JPCardTransactionService.m

https://thedojo.atlassian.net/browse/CT-2814

Implements re-submission logic for soft declined transactions

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/Main/MainViewController.m

It's not the final solution necessarily, but the best I have come up with as far.
The comment may be removed, I would like you to decide whether it's useful or unnecessary. In any case it explains how the fix works, so I don't repeat myself here.

CT-2847 Apple Pay disappearing settings fix

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
Source/Extensions/JPError/JPError+Additions.h
Source/Extensions/JPError/JPError+Additions.m
Source/Resources/en.lproj/Localizable.strings
Source/Resources/es.lproj/Localizable.strings
Source/Resources/fr.lproj/Localizable.strings
Source/Services/ConfigurationValidation/JPConfigurationValidationService.m

Missing validation of Recurring Payment configuration implemented on the SDK level.

CT-2824 Recurring Payment Adjustments

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Base.lproj/Main.storyboard
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Controllers/NoUICardPay/NoUICardPayViewController.m

Adds missing CheckCard to no-UI Demo screen

---

JudoKit_iOSTests/Models/JPConsumerDevice/JPConsumerDeviceTest.swift
JudoKit_iOSTests/Models/JPEnhancedPaymentDetail/JPEnhancedPaymentDetailTest.swift
Source/Models/Browser/JPBrowser.h
Source/Models/Browser/JPBrowser.m
Source/Models/ConsumerDevice/JPConsumerDevice.h
Source/Models/ConsumerDevice/JPConsumerDevice.m
Source/Models/TransactionEnricher/JPRequestEnricher.m

Removes unnecessary params from EnhancedPaymentDetails

---

.circleci/config.yml

Add iPad as a test device on Firebase

CT-3006 | Include iPad in UI testing

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Selectors.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift

Filling in some remaining gaps from our manual regression tests

CT-3019 | Add test for primary account details

---

Source/Helpers/Functions.m

Fixes user agent header not being compliant with RFC

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Extensions/MainViewController+Additions.m
Source/Models/CardDetails/JPCardDetails.h
Source/Models/CardDetails/JPCardDetails.m
Source/Models/Response/JPResponse.h
Source/Models/Response/JPResponse.m
Source/Services/ApiService/Session/JPSession.m

1. Introduces new properties being received from the API: ownerType and emailAddress.
2. Updates Partner API to 6.22.

Updates API the SDK is pointing to 6.22

---

Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Selectors.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/XCUIApplication+Additions.swift

Fixing some changes from previous PRs which have broken some UI tests

UI test fixes

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/project.pbxproj
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/xcshareddata/xcschemes/ObjectiveCExampleAppUITests.xcscheme
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/ObjectiveCExampleAppUITests.xctestplan
fastlane/Fastfile

* Now use Test Plans on ObjC
* Config for running tests on Browserstack

CT-3082 | Introduce additional testing via Browserstack

---

.github/workflows/build-test-publish-sample-apps.yml
.github/workflows/build-test-sample-apps.yml
.github/workflows/build-test-sdk.yml
.github/workflows/publish-sdk.yml

In case we need to manually re-trigger a workflow.

chore: allow github actions to be manually triggered
