Judopay/JudoKit-iOS

Source/Modules/CardCustomization/View/JPCardCustomizationViewController.m
Source/View/FloatingTextField/JPFloatingTextField.m

- Closing and then reopening the app triggers a layout reset. Transformations are lost in the process.
- Changing card patterns triggers a table view reload. If an input field error is visible, it is not reset and remains visible even if the error cause is no longer present.
- Listen to the `UIApplicationWillEnterForegroundNotification` event and manually reset the frame back to the correct position.
- Manually reset the font and error state on every table view reload.
https://thedojo.atlassian.net/browse/EP-782

Fixed the Customization input field movement bug

---

Source/Services/ApplePay/JPApplePayService.m

For some reason, the `JPApplePayService` was looking at the main supported card networks that we use for Judo card transactions, instead of the Apple Pay specific supported networks.

Added fix for the invalid ApplePay supported card networks

---

JudoKit_iOSTests/Models/JPAddress/JPAddressTests.swift
JudoKit_iOSTests/Models/Requests/JPPaymentRequestTests.swift
Source/Models/Address/JPAddress.h
Source/Models/Address/JPAddress.m
Source/Models/Request/JPApplePayRequest.m

Removed hardcoded -1 from the Apple Pay country code that caused issues with the Judo gateway

Apple Pay - Country code fix

---

Source/Services/ConfigurationValidation/JPConfigurationValidationService.m

Our amount validation logic was based on NSNumberFormatter. Depending on your current locale, valid decimal separators are perceived as either `0.15` or `0,15`.

Added fix for locale-specific amount formatting

---

Source/JudoKit.m
Source/Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.m
Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
Source/Services/ApplePay/JPApplePayController.h
Source/Services/ApplePay/JPApplePayController.m

- Tapping on **Cancel** in the Apple Pay sheet will now trigger a *"User did cancel"* callback event;
- Fix an issue with some of the callback events being executed before the UIViewController dismissed, causing the UIAlerts to not display;

Added a "User Cancelled" callback to Apple Pay

---

Examples/ObjectiveCExampleApp/Podfile.lock
JudoKit_iOSTests/Extensions/JPError/JPErrorAdditionsTests.swift
Source/Extensions/JPError/JPError+Additions.m

- The meaningful error message is usually found in two places, the "details" dictionary that is part of the response or in the "message" field. This change checks for both.

Added more robust error handling

---

JudoKit_iOSTests/Extensions/NSString/NSStringAdditionsTests.swift
Source/Extensions/NSString/NSString+Additions.h
Source/Extensions/NSString/NSString+Additions.m
Source/Modules/CardScanController/JPCardScanController.m

Fixes the issue when scanning a card with a unexpected expire date format generates a crash

[CT-2244] - Crash in `JPCardValidationService`

---

Source/Resources/JSON/countries-list.json

The countries.json has been updated with correct value for St. Lucia.

CT-2721 | iOS SDK: Incorrect country code for St. Lucia

---

.circleci/config.yml

The `checkout_project` step is a dependency of the `release_sdk` step, but tags will only trigger a step if it's defined in the filter.

Fix release step

---

Source/View/CardInputView/Subviews/JPBillingInformationForm.m
Source/View/CardInputView/Subviews/JPCardDetailsForm.m
Source/View/InputField/JPInputField.h
Source/View/InputField/JPInputField.m

The modifications in this commit refactor the form text fields to include the appropriate text content type. The changes include adding the `UITextContentType` property to the relevant text fields and setting it to the appropriate content type such as email address, country name, address state, telephone number, street address line 1 and 2, address city, postal code, credit card number, credit card name, credit card expiration, and credit card security code. This ensures that the keyboard suggestions and autofill functionality work correctly for each text field.

Refactor form text fields to include appropriate text content type

---

Source/View/CardInputView/Subviews/JPCardDetailsForm.m
Source/View/InputField/JPInputField.m

- Set `UITextContentTypeCreditCardName` for `_cardHolderNameTextField` if available on iOS 17.0 and above
- Set `UITextContentTypeCreditCardExpiration` for `_expiryDateTextField` if available on iOS 17.0 and above
- Set `UITextContentTypeCreditCardSecurityCode` for `_cardSecurityCodeTextField` if available on iOS 17.0 and above
Additionally, update input field text content type in general:
- Set `UITextContentType` for `self.floatingTextField` if available on iOS 10.0 and above

Update text content type for certain input fields in card input view

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
fastlane/Fastfile

* Configure new job/workflow steps to accommodate testing on previous iOS versions on a weekly basis (every Wed at 12pm UK time)
* Adjust release testing device to iOS 16.6 (was previously 15.7)
* Realised that Firebase does not offer any iOS 17 devices 🤷🏻‍♂️ so put in a request form for this, will see what they say, otherwise look into setting up SauceLabs instead for release testing
* New Slack alerts to differentiate from release testing 🔔 
* PreAuth Payment Methods test was failing so now scrolling to bottom so that feature list item can be tapped without issue
* Add `include_simulator_logs: false` to `fastlane run_tests` config which seems to have fixed the timeout issue we were seeing on CircleCI

CT-2856 | Backward compatibility testing

---

Examples/ObjectiveCExampleApp/Podfile
Examples/ObjectiveCExampleApp/Podfile.lock
Examples/SwiftExampleApp/Podfile
Examples/SwiftExampleApp/Podfile.lock

Replacing Cocoadebug with Wormholy as the first looks to be stagnant and causes network timeouts.
(to trigger Wormholy HTTP requests logger screen - shake your phone)

chore: replacing Cocoadebug with Wormholy as the first looks to be stagnant and causes network timeouts.

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/XCUIApplication+Additions.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift

* iOS 15.2 devices are being deprecated, update to use 15.7
* Refactor 3DS2 `Complete` button handling
* Short pause after generating payment session

Add some more test checks & provisions

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/xcshareddata/xcschemes/ObjectiveCExampleAppUITests.xcscheme
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift

* Skip Ravelin tests until new ones are in
* Skip CA and US billing info tests on lower than iOS 16 devices as the picker wheel just doesn't play nice regardless of what I try on a device with iOS 14/15
* Retry flaky tests 2 times

Backward compatibility UI test fixes

---

Examples/SwiftExampleApp/SwiftExampleApp/Modules/Home/Services/FeatureService.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/NoUICardPay/NoUICardPayView.swift
Examples/SwiftExampleApp/SwiftExampleApp/Modules/NoUICardPay/NoUICardPayViewModel.swift

Before & After
#tested (by me, Eugene not yet)

Unifies No-UI payments screen with Android and ObjectiveC

---

Source/Modules/Transaction/Presenter/JPTransactionPresenter.m
Source/Resources/en.lproj/Localizable.strings
Source/Resources/es.lproj/Localizable.strings
Source/Resources/fr.lproj/Localizable.strings

Fixes typo spotted by Alison. It's better to fix it now, so it looks good in documentation.

Improves strings (missed typo)

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj/xcshareddata/xcschemes/ObjectiveCExampleAppUITests.xcscheme
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Selectors.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/TestData.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/XCUIApplication+Additions.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Ravelin/RavelinUITests.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/CardPayment/CardPaymentUITests.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/Helpers.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/Ideal/IdealUITests.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/Selectors.swift
Examples/SwiftExampleApp/SwiftExampleAppUITests/XCUIApplication+Additions.swift

* Separate iPad and iPhone tests so re-runs take less time
* Remove 3DS2 complete button loop and replace with single wait and tap as this seems more consistent
* Fix issue where halt transaction switch is toggled off for the test
* Add labels to Firebase runs, allow 1 re-run

Reduce test flakiness

---

.circleci/config.yml
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Ideal/IdealUITests.swift
Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Ravelin/RavelinUITests.swift

* Scroll to element before trying to tap (for smaller screen on iPhone 8)
* Wait until element is hittable for pay now button

Small fixes for backward compatibility tests

---

.circleci/config.yml

* Firebase has now introduced an iOS 18 test device built with XCode 16.2 (finally!) so switching to use this for regular regression tests on iPhone. These seem to be slightly faster too (~17mins vs ~24mins).
* Added previously used iOS 16.6 device to the backward compatibility device pool
* Updated for all tests to use XCode 16.2

Firebase test device updates

---

.circleci/config.yml

* iPhone 12 Pro and iOS 14.8 are no longer available so removing this for backward compatibility tests

Remove deprecated Firebase test device
